# Generated by Django 3.0.8 on 2020-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200726_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
