# Generated by Django 3.0.8 on 2020-07-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200726_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
