# Generated by Django 3.0.8 on 2020-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_question',
            old_name='qname',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='text',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='question',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
