# Generated by Django 3.0.8 on 2020-07-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200726_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='nquiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
