# Generated by Django 3.0.8 on 2020-07-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_studentanswer_takenquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='nquiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
