# Generated by Django 3.0.8 on 2020-07-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_studentanswer_takenquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenquiz',
            old_name='tdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='takenquiz',
            old_name='nquiz',
            new_name='quiz',
        ),
    ]
