# Generated by Django 3.0.8 on 2020-07-28 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200717_1055'),
        ('quiz', '0012_auto_20200728_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=0)),
                ('interests', models.ManyToManyField(related_name='interested_students', to='accounts.Subject')),
                ('quizzes', models.ManyToManyField(through='quiz.TakenQuiz', to='quiz.Quiz')),
            ],
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='quiz.temp'),
        ),
    ]
