# Generated by Django 3.0.8 on 2020-07-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200728_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='score',
        ),
    ]
