# Generated by Django 3.0.8 on 2020-07-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200731_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='starttime',
        ),
    ]
