# Generated by Django 3.0.8 on 2020-07-22 14:27

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='topics/documents/', validators=[forum.validators.validate_file_extension]),
        ),
    ]
