# Generated by Django 3.0.7 on 2020-07-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200717_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.Subject'),
        ),
    ]
