# Generated by Django 3.0.8 on 2020-07-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='document',
        ),
    ]
