# Generated by Django 3.0.8 on 2020-07-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200717_1055'),
        ('course_materials', '0002_remove_coursematerial_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='accounts.Subject'),
        ),
    ]
