# Generated by Django 3.0.8 on 2020-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/announcements'),
        ),
    ]
