# Generated by Django 3.0.8 on 2020-07-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20200724_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/announcements'),
        ),
    ]
